language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
services:
  - postgresql
env:
  global:
    - APP_SETTINGS=testing
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - pytest app/tests --cov=app/views --cov-report term-missing
after_success:
  - coveralls
